@extends('layouts.pharmacy')
@section('title', $customer->name.' — '.__('pharmacy.product'))
@section('content')
<div class="mx-auto max-w-7xl space-y-5">
    <div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p class="text-sm font-semibold text-teal-700">Customer account</p><h1 class="text-3xl font-bold">{{ $customer->name }}</h1><p class="mt-1 text-sm text-slate-500">{{ $customer->phone ?: 'No phone' }}{{ $customer->email ? ' · '.$customer->email : '' }}</p></div><a href="{{ route('pharmacy.customers.edit', $customer) }}" class="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold">Edit customer</a></div>
    <section class="grid gap-4 sm:grid-cols-3"><article class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-sm text-slate-500">Lifetime sales</p><p class="mt-2 text-2xl font-bold">{{ number_format((float) $salesTotal, 2) }} AFN</p></article><article class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-sm text-slate-500">Outstanding credit</p><p class="mt-2 text-2xl font-bold text-amber-700">{{ number_format((float) $outstandingCredit, 2) }} AFN</p></article><article class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-sm text-slate-500">Credit limit</p><p class="mt-2 text-2xl font-bold">{{ number_format((float) $customer->credit_limit, 2) }} AFN</p></article></section>
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-bold">Sales history</h2></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-4 py-3 text-start">Sale</th><th class="px-4 py-3 text-start">Date</th><th class="px-4 py-3 text-end">Total</th><th class="px-4 py-3 text-end">Due</th><th class="px-4 py-3 text-end">Receipt</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($sales as $sale)<tr><td class="px-4 py-3 font-semibold">{{ $sale->sale_number }}</td><td class="px-4 py-3">{{ $sale->business_date?->toDateString() }}</td><td class="px-4 py-3 text-end">{{ number_format((float)$sale->grand_total,2) }} AFN</td><td class="px-4 py-3 text-end">{{ number_format((float)$sale->due_total,2) }} AFN</td><td class="px-4 py-3 text-end"><a class="font-semibold text-teal-700" href="{{ route('pharmacy.pos.receipt',$sale) }}">Open</a></td></tr>@empty<tr><td colspan="5" class="px-4 py-10 text-center text-slate-500">No completed sales yet.</td></tr>@endforelse</tbody></table></div>@if($sales->hasPages())<div class="border-t border-slate-100 px-4 py-3">{{ $sales->links() }}</div>@endif</section>
</div>
@endsection
